jobs:
  include:
  - name: "Build Staging Branch"
    if: branch = staging
    language: node_js
    node_js:
      - "10.14.2"
    cache: npm

    before_install:
    install: 
      - npm ci
    before_script:
      - npm install -g gatsby-cli

    script:
      - GATSBY_ACTIVE_ENV=staging gatsby build


    after_success:
    after_failure:

    after_script:

    before_deploy:

    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      target_branch: gh-pages
      local_dir: public
      on:
        branch: staging
      # provider: firebase
      # token:
      #   secure: $FIREBASE_TOKEN
      # project: "studio-gurr"
      # message: "Deployed with Travis"

    after_deploy:
    - name: "Build Development Branch"
    if: branch = development
    language: node_js
    node_js:
      - "10.14.2"
    cache: npm

    before_install:
    install: 
      - npm ci
    before_script:
      - npm install -g gatsby-cli

    script:
      - GATSBY_ACTIVE_ENV=staging gatsby build


    after_success:
    after_failure:

    after_script:

    before_deploy:

    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep_history: true
      target_branch: gh-pages
      local_dir: public
      on:
        branch: development
      # provider: firebase
      # token:
      #   secure: $FIREBASE_TOKEN
      # project: "studio-gurr"
      # message: "Deployed with Travis"

    after_deploy:

