language: node_js
node_js:
  - "10.14.2"

cache: 
  npm: true
  directories:
    - "node_modules"


before_install:

install: 
  - npm ci
  - npm install -g firebase-tools

before_script:
  - npm install -g gatsby-cli

script:
  # - GATSBY_ACTIVE_ENV=production gatsby build
  - gatsby build
  - echo "Deploying"


after_success:
  - firebase deploy --token $FIREBASE_TOKEN

after_failure:

after_script:

before_deploy:

deploy:
  # provider: pages
  # skip_cleanup: true
  # github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # keep_history: true
  # target_branch: gh-pages
  # local_dir: public
  # on:
  #   branch: staging

after_deploy:
