language: node_js
before_script:
  - npm install -g gatsby-cli
  - npm install
node_js:
  - "10"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: development